apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-parser-service
  labels:
    app: ai-parser-service
spec:
  replicas: 1  # Start with 1 replica for AI service due to API costs
  selector:
    matchLabels:
      app: ai-parser-service
  template:
    metadata:
      labels:
        app: ai-parser-service
    spec:
      containers:
      - name: ai-parser-service
        image: biteme/ai-parser-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: AI_SERVICE_PORT
          value: "3003"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: gemini-api-key
        - name: CONFIDENCE_THRESHOLD
          value: "0.7"
        - name: MAX_RETRY_ATTEMPTS
          value: "3"
        - name: AI_TIMEOUT
          value: "30000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ai-parser-service
spec:
  selector:
    app: ai-parser-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-parser-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-parser-service
  minReplicas: 1
  maxReplicas: 5  # Lower max due to AI API costs
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
