apiVersion: apps/v1
kind: Deployment
metadata:
  name: biteme-client
  labels:
    app: biteme-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: biteme-client
  template:
    metadata:
      labels:
        app: biteme-client
    spec:
      containers:
      - name: biteme-client
        image: biteme/client:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.biteme.com/api"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: biteme-client
spec:
  selector:
    app: biteme-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biteme-client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - biteme.com
    - www.biteme.com
    secretName: biteme-client-tls
  rules:
  - host: biteme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: biteme-client
            port:
              number: 3000
  - host: www.biteme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: biteme-client
            port:
              number: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: biteme-client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: biteme-client
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
