apiVersion: apps/v1
kind: Deployment
metadata:
  name: meals-service
  labels:
    app: meals-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meals-service
  template:
    metadata:
      labels:
        app: meals-service
    spec:
      containers:
      - name: meals-service
        image: biteme/meals-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: MEALS_DB_URI
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: meals-db-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: jwt-secret
        - name: MEALS_SERVICE_PORT
          value: "3002"
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: biteme-secrets
              key: cloudinary-api-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: meals-service
spec:
  selector:
    app: meals-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meals-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meals-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
